version: '3.3'
services:
  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "python manage.py collectstatic --noinput && python manage.py makemigrations && python manage.py migrate && python manage.py loaddata authapp/fixtures/001_custom_user.json authapp/fixtures/003_post.json authapp/fixtures/004_comment_model.json authapp/fixtures/005_like_model.json authapp/fixtures/006_dislike_model.json authapp/fixtures/007_message.json && gunicorn web.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
      - redis
    volumes:
      - .:/web
    env_file:
      - ./.env
    networks:
      - web_mynetwork

  daphne:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - ./.env
    volumes:
      - .:/web
    networks:
      - web_mynetwork

  db:
    image: mysql:8
    container_name: my_mysql_db
    ports:
      - "3306:3306"
    volumes:
      - .:/web
    env_file:
      - ".env"
    networks:
      - web_mynetwork

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - web_mynetwork

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - django
    links:
      - django:web
    volumes:
      - .:/web
    networks:
      - web_mynetwork

networks:
  web_mynetwork:
    driver: bridge

#services:
#  gb_dev_db:
#    build: ./configs/db/
#    container_name: gb_dev_db
#    ports:
#      - "3300:3300"
#    env_file:
#      - ".env"

