version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3333:3333"
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: always

#services:
#  gb_dev_db:
#    build: ./configs/db/
#    container_name: gb_dev_db
#    ports:
#      - "3300:3300"
#    env_file:
#      - ".env"

