version: '3.3'
services:
  db:
    image: mysql:8
    container_name: my_mysql_db
    ports:
      - "3306:3306"
    env_file:
      - ".env"
#  redis:
#    image: redis
#    ports:
#      - "6379:6379"

#services:
#  gb_dev_db:
#    build: ./configs/db/
#    container_name: gb_dev_db
#    ports:
#      - "3300:3300"
#    env_file:
#      - ".env"

